ALTER TABLE users
  ADD COLUMN IF NOT EXISTS address_line1 TEXT,
  ADD COLUMN IF NOT EXISTS address_line2 TEXT,
  ADD COLUMN IF NOT EXISTS city          TEXT,
  ADD COLUMN IF NOT EXISTS state         VARCHAR(2),
  ADD COLUMN IF NOT EXISTS zip           VARCHAR(10);
